# Generated by Django 4.2.1 on 2024-01-15 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="purpose",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
