# Generated by Django 4.2.1 on 2023-06-11 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Office_name",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("office_name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contracts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_of_contract", models.CharField(max_length=200)),
                ("contract_with", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("contract_date", models.DateField(blank=True, null=True)),
                ("billing_date", models.DateField(blank=True, null=True)),
                ("amount", models.IntegerField(null=True)),
                ("payment_status", models.BooleanField(default=False, null=True)),
                ("status", models.IntegerField(default=1)),
                ("contract_file", models.FileField(upload_to="media/")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contracts.office_name",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contract_actions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.IntegerField(default=1)),
                ("amount", models.IntegerField(blank=True)),
                ("extra", models.JSONField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="contracts.contracts",
                    ),
                ),
            ],
        ),
    ]
