# Generated by Django 4.2.1 on 2023-06-16 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contracts", "0003_alter_contract_actions_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract_actions",
            name="remarks",
            field=models.TextField(default=2, max_length=20000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contract_actions",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contracts.contracts"
            ),
        ),
        migrations.AlterField(
            model_name="contract_actions",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
