# Generated by Django 4.2.1 on 2023-06-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_contract_actions_remarks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract_actions",
            name="remarks",
            field=models.TextField(blank=True, max_length=20000, null=True),
        ),
    ]
