# Generated by Django 4.2.1 on 2023-06-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0006_roles_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
