# Generated by Django 4.2.1 on 2023-06-16 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0007_alter_profile_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="roles", name="code",),
    ]
