# Generated by Django 4.2.1 on 2023-06-21 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0008_remove_roles_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="CLient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("contact_person", models.CharField(max_length=200)),
                ("mobile", models.CharField(max_length=15)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(model_name="contracts", name="contract_with",),
        migrations.AlterField(
            model_name="contracts",
            name="contract_file",
            field=models.FileField(upload_to="media"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
        migrations.AddField(
            model_name="contracts",
            name="client",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="contracts.client",
            ),
            preserve_default=False,
        ),
    ]
