# Generated by Django 4.2.1 on 2023-06-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0009_client_remove_contracts_contract_with_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="contact_person",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="mobile",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
