# Generated by Django 4.2.1 on 2023-07-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0010_alter_client_contact_person_alter_client_mobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contracts", name="amount", field=models.FloatField(null=True),
        ),
    ]
