# Generated by Django 4.2.1 on 2023-07-12 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0011_alter_contracts_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_year", models.DateField()),
                ("end_year", models.DateField()),
                ("status", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(model_name="contracts", name="address",),
        migrations.AddField(
            model_name="contracts",
            name="fiscalyear",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="contracts.fiscalyear",
            ),
        ),
    ]
