# Generated by Django 4.2.1 on 2023-07-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0012_fiscalyear_remove_contracts_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fiscalyear",
            name="end_year",
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name="fiscalyear",
            name="start_year",
            field=models.CharField(max_length=4),
        ),
    ]
