# Generated by Django 4.2.1 on 2023-08-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0013_alter_fiscalyear_end_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contracts",
            name="comission",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
