# Generated by Django 4.2.1 on 2023-08-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0014_contracts_comission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contracts",
            name="comission",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
