# Generated by Django 4.2.1 on 2023-08-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0015_alter_contracts_comission"),
    ]

    operations = [
        migrations.RemoveField(model_name="contracts", name="comission",),
    ]
