# Generated by Django 4.2.1 on 2023-08-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0016_remove_contracts_comission"),
    ]

    operations = [
        migrations.AddField(
            model_name="contracts",
            name="comission",
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
