# Generated by Django 4.2.1 on 2023-08-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0017_contracts_comission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contracts",
            name="comission",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
