# Generated by Django 4.2.1 on 2023-11-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0018_alter_contracts_comission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contracts",
            name="comission",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
