# Generated by Django 4.2.1 on 2023-11-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0019_alter_contracts_comission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contracts",
            name="comission",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
