# Generated by Django 4.2.1 on 2023-12-28 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0020_alter_contracts_comission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contracts",
            name="contract_file",
            field=models.FileField(
                upload_to="media",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "PDF"]
                    )
                ],
            ),
        ),
    ]
