# Generated by Django 4.2.1 on 2024-05-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0021_alter_contracts_contract_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='contract_file',
            field=models.FileField(upload_to='media'),
        ),
    ]
