# Generated by Django 4.2.1 on 2024-05-22 21:31

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0022_alter_contracts_contract_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='office_name',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=contracts.models.office_docuemnt_path),
        ),
        migrations.AddField(
            model_name='office_name',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='office_name',
            name='pan_no',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
