# Generated by Django 4.2.1 on 2024-08-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0023_office_name_document_office_name_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='office_name',
            name='pan_no',
            field=models.IntegerField(null=True),
        ),
    ]
