# Generated by Django 4.2.1 on 2024-08-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0024_profile_otp_alter_office_name_pan_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='otp',
            field=models.BooleanField(default=False),
        ),
    ]
