# Generated by Django 4.2.1 on 2024-09-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0026_otptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='otptoken',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
