# Generated by Django 4.2.1 on 2024-09-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0027_otptoken_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
