# Generated by Django 4.2.1 on 2024-09-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0028_alter_otptoken_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='deleted_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
