# Generated by Django 4.2.1 on 2024-09-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0029_alter_otptoken_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
