# Generated by Django 4.2.1 on 2024-11-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='extra',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
