# Generated by Django 4.2.1 on 2024-11-22 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasksboard', '0002_comment_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='tasksboard.card'),
        ),
    ]
