# Generated by Django 4.2.1 on 2024-02-08 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contracts", "0021_alter_contracts_contract_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Unpaid"),
                            (1, "Partly Paid"),
                            (2, "Overdue"),
                            (3, "Paid"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "number_of_invoice",
                    models.CharField(max_length=10, verbose_name="Number of invoice"),
                ),
                ("date_of_issue", models.DateField(verbose_name="Issue Date")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "Contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contracts.contracts",
                    ),
                ),
            ],
            options={"verbose_name": "Invoice", "verbose_name_plural": "Invoices",},
        ),
        migrations.CreateModel(
            name="InvoiceTracks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.PositiveSmallIntegerField()),
                ("description", models.TextField()),
                ("amount", models.FloatField(blank=True, null=True)),
                ("rate", models.FloatField(blank=True, null=True)),
                ("total", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="invoice.invoices",
                    ),
                ),
            ],
        ),
    ]
