# Generated by Django 4.2.1 on 2024-02-28 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0021_alter_contracts_contract_file"),
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="invoices", name="Contract",),
        migrations.RemoveField(model_name="invoices", name="deleted_at",),
        migrations.RemoveField(model_name="invoicetracks", name="total",),
        migrations.AddField(
            model_name="invoices",
            name="client",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="contracts.client",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoices",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoicetracks",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoicetracks",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoicetracks",
            name="status",
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoicetracks",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="invoices",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="invoices", name="date_of_issue", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="invoicetracks",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="invoices",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contracts.contracts",
            ),
        ),
    ]
